PRIMITIVES=[
"TEXT","EQUATION","SHAPE","ARROW","ICON","DIAGRAM","CHART",
"PARTICLE","PATH","GROUP","IMAGE","LABEL","HIGHLIGHT","MASK"
]
ANIMATIONS=[
"APPEAR","FADE","WRITE","DRAW","TRANSFORM","MOVE","SCALE",
"ROTATE","MORPH","HIGHLIGHT","REVEAL","WIGGLE","TRACE","PULSE"
]
