from __future__ import annotations
from .provenance_adapter import all_refs
from .contracts import *
from .security import validate_generated_source

def compile_runtime_controller(ctx:CompilerContext):
    ctx.validate()
    ts=r'''import {stateMachine, cloneState, type RuntimeState} from "./state-machine";
import {ruleMetadata, ruleFunctions} from "./rules";
import {interactionProgram} from "./interactions";
import {scoringProgram} from "./scoring";
import {feedbackProgram} from "./feedback";
import {adaptationMetadata, adaptationFunctions} from "./adaptation";
import {telemetryProgram, sanitizeTelemetry} from "./telemetry";
import {applySemanticState} from "./react-runtime";
type DispatchResult={applied:boolean;action_id:string;rule_id:string|null;mechanic_id:string;state:RuntimeState;score:number;feedback:string;adaptations:readonly string[];telemetry:Record<string,unknown>};
function levelState(levelId:string):RuntimeState {const levels=(stateMachine.games as readonly any[]).flatMap((g:any)=>g.levels);const level=levels.find((x:any)=>x.level_id===levelId);if(!level)throw new Error("GAME_RUNTIME_LEVEL_STATE_MISSING");const out:RuntimeState={};for(const v of level.variables)out[v.id]=v.initial;return out;}
function applyEffects(state:RuntimeState,effects:readonly any[]):RuntimeState {const next=cloneState(state);for(const e of effects){const cur:any=next[e.target];if(e.kind==="set")next[e.target]=e.value;else if(e.kind==="add")next[e.target]=Number(cur)+Number(e.value);else if(e.kind==="sub")next[e.target]=Number(cur)-Number(e.value);else if(e.kind==="mul")next[e.target]=Number(cur)*Number(e.value);else if(e.kind==="div"){if(Number(e.value)===0)throw new Error("GAME_RUNTIME_DIV_ZERO");next[e.target]=Number(cur)/Number(e.value);}else if(e.kind==="toggle")next[e.target]=!Boolean(cur);else throw new Error("GAME_RUNTIME_EFFECT_UNSUPPORTED");}return next;}
export function createRuntimeController(levelId:string){let state=levelState(levelId),score=0,attempts=0,lastFeedback="Ready";const telemetry:Record<string,unknown>[]=[];const actions=(interactionProgram.actions_and_events as readonly any[]).filter((x:any)=>x.level_id===levelId&&x.action_id);
 function dispatch(actionId:string,payload:Record<string,unknown>={}):DispatchResult{const action=actions.find((x:any)=>x.action_id===actionId);if(!action)throw new Error("GAME_RUNTIME_ACTION_UNKNOWN");if(action.mechanic_id==="reset"){state=levelState(levelId);applySemanticState(state,levelId);return{applied:true,action_id:actionId,rule_id:null,mechanic_id:action.mechanic_id,state:cloneState(state),score,feedback:"Reset",adaptations:[],telemetry:{}};}const meta=(ruleMetadata.rules as readonly any[]).find((x:any)=>x.rule_id===action.rule_id&&x.level_id===levelId);if(!meta)throw new Error("GAME_RUNTIME_RULE_ROUTE_MISSING");const predicate=ruleFunctions[action.rule_id];if(!predicate)throw new Error("GAME_RUNTIME_RULE_FUNCTION_MISSING");if(!predicate(state))return{applied:false,action_id:actionId,rule_id:action.rule_id,mechanic_id:action.mechanic_id,state:cloneState(state),score,feedback:lastFeedback,adaptations:[],telemetry:{}};state=applyEffects(state,meta.effects);attempts++;const gameId=(stateMachine.games as readonly any[]).find((g:any)=>g.levels.some((l:any)=>l.level_id===levelId))?.game_id;const scoring=(scoringProgram.games as any)[gameId];if(scoring)score=Math.max(Number(scoring.floor||0),score+Number(scoring.correct_points||0));const challengeId=(action.challenge_ids||[])[0];const fb=(feedbackProgram.feedback as readonly any[]).find((x:any)=>x.challenge_id===challengeId);lastFeedback=fb?.success||"Correct";const fired:string[]=[];for(const a of adaptationMetadata.rules as readonly any[]){if(a.level_id!==levelId)continue;const fn=adaptationFunctions[a.adaptation_id];if(fn&&fn(state))fired.push(a.action+":"+(a.target_id||""));}const event=sanitizeTelemetry({event:"mechanic_completed",game_id:gameId,level_id:levelId,challenge_id:challengeId,attempt_number:attempts,outcome_code:"applied",mechanic_id:action.mechanic_id});if((telemetryProgram.events as readonly string[]).includes("mechanic_completed"))telemetry.push(event);applySemanticState(state,levelId);const out=document.getElementById("bie-game-feedback");if(out)out.textContent=lastFeedback;return{applied:true,action_id:actionId,rule_id:action.rule_id,mechanic_id:action.mechanic_id,state:cloneState(state),score,feedback:lastFeedback,adaptations:fired,telemetry:event};}
 function bind(root:HTMLElement){for(const action of actions){const target=root.querySelector(`[data-entity-id="${action.target}"]`) as HTMLElement|null;if(!target)throw new Error("GAME_RUNTIME_ACTION_TARGET_MISSING");const invoke=(payload:Record<string,unknown>={})=>dispatch(action.action_id,payload);target.addEventListener("click",()=>invoke({}));target.addEventListener("keydown",(ev:KeyboardEvent)=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();invoke({});}else if(action.kind==="adjust"&&(ev.key==="ArrowRight"||ev.key==="ArrowUp")){ev.preventDefault();invoke({delta:1});}});if(action.kind==="drag"||action.kind==="drop"||action.kind==="place")target.addEventListener("pointerup",(ev:PointerEvent)=>invoke({x:ev.clientX,y:ev.clientY}));}}
 return Object.freeze({dispatch,bind,getState:()=>cloneState(state),getScore:()=>score,getFeedback:()=>lastFeedback,getTelemetry:()=>telemetry.slice(),actionIds:()=>actions.map((x:any)=>x.action_id)});}
'''
    validate_generated_source(ts,allow_imports=True);return artifact(ArtifactKind.RUNTIME_CONTROLLER,'runtime/runtime-controller.ts','text/typescript',ts,all_refs(ctx.document.provenance))
