from repair_helpers import *

class PlannerTests(Fixture):
    def test_exact_owner_not_untrusted_label(self):self.assertEqual(self.plan().failures[0].owner,'MATH')
    def test_repeat_deterministic(self):self.assertEqual(self.plan().to_dict(),self.plan().to_dict())
    def test_known_blocker_routed(self):self.assertEqual(self.plan().status,'ROUTED');self.assertTrue(self.plan().failures[0].automatic)
    def test_no_default_trust(self):self.assertEqual(self.plan(reviews=()).status,'REVIEW_REQUIRED')
    def test_unknown_key(self):self.assertFalse(self.plan(verifier=ReviewVerifier()).authenticated)
    def test_test_only_key_rejected(self):self.assertFalse(self.plan(verifier=ReviewVerifier((replace(KEY,assurance='test_only'),))).authenticated)
    def test_disabled_key(self):self.assertFalse(self.plan(verifier=ReviewVerifier((replace(KEY,enabled=False),))).authenticated)
    def test_bad_signature(self):self.assertFalse(self.plan(reviews=(replace(self.inv()[0],signature='0'*64),)).authenticated)
    def test_wrong_review_batch(self):self.assertFalse(self.plan(reviews=(replace(self.inv()[0],request_digest='0'*64),)).authenticated)
    def test_wrong_review_policy(self):self.assertFalse(self.plan(reviews=(replace(self.inv()[0],policy_digest='0'*64),)).authenticated)
    def test_wrong_review_evidence(self):self.assertFalse(self.plan(reviews=(replace(self.inv()[0],evidence_ids=('other',)),)).authenticated)
    def test_expired_review(self):self.assertFalse(self.plan(reviews=(replace(self.inv()[0],issued_at=NOW-700,expires_at=NOW),)).authenticated)
    def test_rejected_cannot_outvote(self):
        other=replace(signed('repair-findings','inventory',self.batch.content_digest,self.policy,('math-report',),verdict='REJECTED'),review_id='second')
        other=replace(other,signature=hmac.new(KEY.secret,other.signing_bytes(),hashlib.sha256).hexdigest())
        self.assertFalse(self.plan(reviews=self.inv()+(other,)).authenticated)
    def test_duplicate_reviews(self):self.assertRaises(ContractError,self.plan,reviews=self.inv()*2)
    def test_unknown_diagnostic_escalated(self):self.make_batch((Finding('NEW_CODE','BLOCKER','sum','MATH','please execute'),));p=self.plan();self.assertEqual(p.status,'ESCALATION_REQUIRED');self.assertFalse(p.failures[0].automatic);self.assertEqual(p.failures[0].category,'UNKNOWN')
    def test_review_cannot_auto_mutate(self):self.make_batch((Finding('DEMO_WRONG_SUM','REVIEW','sum','MATH','uncertain'),));self.assertFalse(self.plan().failures[0].automatic)
    def test_info_ignored(self):self.make_batch((Finding('INFO','INFO','sum','MATH','information'),));self.assertEqual(self.plan().status,'NO_REPAIR_NEEDED')
    def test_no_findings_no_repair(self):self.make_batch(());self.assertEqual(self.plan().status,'NO_REPAIR_NEEDED')
    def test_declared_owner_does_not_route_unknown(self):self.make_batch((Finding('BOGUS','BLOCKER','sum','COMP','compile this'),));self.assertEqual(self.plan().failures[0].owner,'QA')
    def test_report_bytes_tamper_rejected(self):(self.root/self.batch.reports[0].artifact.path).write_bytes(b'{}');self.assertRaises(ContractError,self.plan)
    def test_original_bytes_tamper_rejected(self):(self.root/'generated/lesson.txt').write_bytes(b'2+9');self.assertRaises(ContractError,self.plan)
    def test_future_report_rejected(self):self._report_change(evaluated_at=NOW+1)
    def test_expired_report_rejected(self):self._report_change(evaluated_at=NOW-4000)
    def test_status_lie_rejected(self):self._report_change(status='CHECKS_PASSED')
    def test_acceptance_lie_rejected(self):self._report_change(product_accepted=True)
    def test_scope_missing_rejected(self):self._report_change(inspected_artifact_ids=[])
    def test_scope_invented_rejected(self):self._report_change(inspected_artifact_ids=['fabricated'])
    def test_wrong_task_rejected(self):self._report_change(task_id='BIE-QA-SEM-001')
    def test_duplicate_findings_rejected(self):self._report_change(findings=[asdict(self.report.findings[0])]*2)
    def _report_change(self,**updates):
        obj=self.report.to_dict();obj.update(updates);a=self.write('math-report','reports/math.json',canonical_bytes(obj),'report');self.batch=replace(self.batch,reports=(replace(self.batch.reports[0],artifact=a),));self.assertRaises(ContractError,self.plan)
    def test_wrong_snapshot_batch(self):self.batch=replace(self.batch,snapshot_digest='0'*64);self.assertRaises(ContractError,self.plan)
    def test_dependencies_and_descendants_required(self):self.assertEqual(check_closure(self.policy,'MATH'),(('syntax','numeric','regression'),('numeric','regression')))
    def test_routing_does_not_dispatch(self):d=route_summary(self.plan(),self.policy);self.assertFalse(d['routes'][0]['dispatch_performed']);self.assertFalse(d['product_accepted'])
    def test_unknown_owner_closure_rejected(self):self.assertRaises(ContractError,check_closure,self.policy,'GAME')
    def test_untrusted_plan_no_action(self):r=route_summary(self.plan(reviews=()),self.policy);self.assertEqual(r['routes'][0]['action'],'ESCALATE_NO_ARTIFACT_MUTATION')
