STATES = [
    "INGESTED","UNDERSTOOD","PLANNED","SCRIPTED","STORYBOARDED",
    "ASSETS_READY","AUDIO_READY","COMPOSED","RENDERED","QA_EVALUATED",
    "REMEDIATION","VERIFIED","FAILED","CANCELLED"
]

TERMINAL_STATES = {"VERIFIED","FAILED","CANCELLED"}

TRANSITIONS = {
    "INGESTED":{"UNDERSTOOD","FAILED","CANCELLED"},
    "UNDERSTOOD":{"PLANNED","FAILED","CANCELLED"},
    "PLANNED":{"SCRIPTED","FAILED","CANCELLED"},
    "SCRIPTED":{"STORYBOARDED","FAILED","CANCELLED"},
    "STORYBOARDED":{"ASSETS_READY","FAILED","CANCELLED"},
    "ASSETS_READY":{"AUDIO_READY","FAILED","CANCELLED"},
    "AUDIO_READY":{"COMPOSED","FAILED","CANCELLED"},
    "COMPOSED":{"RENDERED","FAILED","CANCELLED"},
    "RENDERED":{"QA_EVALUATED","FAILED","CANCELLED"},
    "QA_EVALUATED":{"VERIFIED","REMEDIATION","FAILED","CANCELLED"},
    "REMEDIATION":{"ASSETS_READY","AUDIO_READY","COMPOSED","RENDERED",
                    "QA_EVALUATED","FAILED","CANCELLED"}
}

def can_transition(current, target):
    return target in TRANSITIONS.get(current, set())
