def external_node(node_id,name,reason,derived_from,confidence=.60):
    return {
      "id":node_id,"type":"external_knowledge","name":name,
      "source_scope":"EXTERNAL_HIGHER_KNOWLEDGE",
      "confidence":confidence,
      "derived_from":derived_from,
      "reason":reason,
      "requires_verification":True
    }

def external_edge(source,target,relation,reason,confidence=.60):
    return {
      "source":source,"target":target,"relation":relation,
      "source_scope":"EXTERNAL_HIGHER_KNOWLEDGE",
      "confidence":confidence,
      "reason":reason,
      "requires_verification":True
    }

def propose_higher_knowledge(book_nodes, candidates):
    # Candidates must be generated by a later research/model layer.
    out_nodes=[]; out_edges=[]
    for c in candidates:
        base=c.get("derived_from")
        if base in {n["id"] for n in book_nodes}:
            out_nodes.append(external_node(
                c["id"],c["name"],c["reason"],[base],c.get("confidence",.60)
            ))
            if c.get("target"):
                out_edges.append(external_edge(
                    base,c["id"],c.get("relation","extends"),
                    c["reason"],c.get("confidence",.60)
                ))
    return out_nodes,out_edges
