STATES={
 "course":{"CREATED","QUEUED","RUNNING","PAUSED","CANCELLED","COMPLETED","FAILED","AWAITING_APPROVAL","RELEASED"},
 "lesson":{"CREATED","QUEUED","RUNNING","PAUSED","CANCELLED","COMPLETED","FAILED"},
 "scene":{"CREATED","QUEUED","RUNNING","PAUSED","CANCELLED","COMPLETED","FAILED"},
 "run":{"CREATED","QUEUED","RUNNING","PAUSED","CANCELLED","COMPLETED","FAILED","AWAITING_APPROVAL","RELEASED"}
}
TRANSITIONS={
 "CREATED":{"QUEUED","CANCELLED"},
 "QUEUED":{"RUNNING","CANCELLED"},
 "RUNNING":{"PAUSED","COMPLETED","FAILED","CANCELLED"},
 "PAUSED":{"RUNNING","CANCELLED","FAILED"},
 "COMPLETED":{"AWAITING_APPROVAL"},
 "AWAITING_APPROVAL":{"RELEASED","FAILED"},
 "FAILED":{"QUEUED","CANCELLED"},
 "CANCELLED":{"QUEUED"},
 "RELEASED":set()
}
def valid_transition(current,target):
 return target in TRANSITIONS.get(current,set())
