"""Real durable Visual interruption, fencing and restart controls.

Test-only lease expiry models process loss without altering production timeouts.
All predecessor artifacts are generated by the actual native PDF producer. Each
Visual execution and recovery occurs afresh in a closed SQLite/CAS copy.
"""
from contextlib import closing
import json
import sqlite3
import unittest

from test_visual_producer import PreparedVisualFixture
from bie.productization.director_storage import native_runtime


class WorkerInterrupted(BaseException):
    """Process-loss stand-in outside ordinary stage failure handling."""


class VisualRecoveryTests(PreparedVisualFixture):
    def crash(self, phase):
        self.until_visual()
        def fault(current):
            if current == phase:
                raise WorkerInterrupted()
        with self.assertRaises(WorkerInterrupted):
            self.step(fault=fault)

    def expire_test_lease(self):
        with self.port.native(self.p, self.run, "read") as service:
            with service.leases.db:
                service.leases.db.execute("UPDATE director_leases SET expires_at=0 WHERE state='ACTIVE'")

    def recover_and_finish(self):
        self.expire_test_lease()
        self.port.recover(self.p, self.run)
        result = self.step()
        self.assertTrue(result["slice_complete"], result.get("safe_diagnostics"))
        self.assertEqual(result["stages"]["VISUAL"], "SUCCEEDED")
        self.assertTrue(all(v == "NOT_RUN" for v in result["downstream"].values()))
        self.assertEqual(self.stack.calls, dict(generator=0, critic=0, annotator=0, reviewer=0))
        return result

    def assert_retained_interruption(self):
        with self.port.native(self.p, self.run, "read") as service:
            history = service.persistence.load_run_state(self.run)["stages"]["VISUAL"]["attempts"]
            self.assertEqual([row["state"] for row in history], ["FAILED", "SUCCEEDED"])
            self.assertTrue(history[0]["evidence_refs"])
            recovery = service.read(self.run, history[0]["evidence_refs"][-1])
            self.assertEqual(recovery["code"], "interrupted_attempt")
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 1)).state, "DEAD_LETTER")
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 2)).state, "ACKED")

    def candidate_identity(self):
        with self.port.native(self.p, self.run, "read") as service:
            with native_runtime(service, self.run, None) as runtime:
                rows = [r for r in runtime.io.catalog.records.values()
                        if r.artifact_type == "director.visual_sync_candidate"]
                self.assertEqual(len(rows), 1)
                return runtime.io.load(rows[0].artifact_id).to_ref()

    def test_intent_derivation_interruption_retains_attempt_and_recovers(self):
        self.crash("after_VISUAL_intent_derivation")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_native_sync_candidate_interruption_reuses_exact_native_identity(self):
        self.crash("after_VISUAL_sync_candidate")
        identity = self.candidate_identity()
        self.recover_and_finish()
        self.assert_retained_interruption()
        self.assertEqual(self.candidate_identity(), identity)

    def test_current_inputs_cas_before_record_interruption_recovers(self):
        self.crash("after_VISUAL_visual.current_inputs_cas")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_internal_stage_cas_interruption_recovers(self):
        self.crash("after_VISUAL_visual.stage_cas")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_validation_evidence_cas_interruption_recovers(self):
        self.crash("after_VISUAL_visual.validation_cas")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_animation_compatible_handoff_cas_interruption_recovers(self):
        self.crash("after_VISUAL_visual.handoff_cas")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_visual_plan_cas_before_terminal_interruption_recovers(self):
        self.crash("after_VISUAL_visual.plan_cas")
        self.recover_and_finish()
        self.assert_retained_interruption()

    def test_safe_receipt_cas_interruption_recovers_without_director_reexecution(self):
        self.crash("after_VISUAL_producer.evidence_cas")
        identity = self.candidate_identity()
        self.recover_and_finish()
        self.assertEqual(self.candidate_identity(), identity)
        self.assert_retained_interruption()

    def test_terminal_before_ack_preserves_exact_plan_and_attempt(self):
        self.crash("after_VISUAL_terminal")
        before = self.visual()
        with self.port.native(self.p, self.run, "read") as service:
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 1)).state, "DELIVERED")
        self.recover_and_finish()
        self.assertEqual(self.visual(), before)
        with self.port.native(self.p, self.run, "read") as service:
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 1)).state, "ACKED")
            history = service.persistence.load_run_state(self.run)["stages"]["VISUAL"]["attempts"]
            self.assertEqual(len(history), 1)
            self.assertEqual(history[0]["state"], "SUCCEEDED")

    def test_ack_before_downstream_boundary_never_executes_animation(self):
        self.crash("before_next_admission")
        before = self.visual()
        result = self.step()
        self.assertTrue(result["slice_complete"])
        self.assertEqual(self.visual(), before)
        self.assertEqual(result["downstream"]["ANIMATION"], "NOT_RUN")

    def test_live_outer_lease_cannot_be_recovered(self):
        self.crash("after_VISUAL_intent_derivation")
        with self.assertRaises(Exception):
            self.port.recover(self.p, self.run)

    def test_stale_visual_writer_cannot_publish_private_artifact(self):
        with self.port.native(self.p, self.run, "worker") as service:
            service.active_lease = service.leases.acquire("stale-visual-control", "intent",
                service.owner, now=0, ttl_seconds=1)
            with self.assertRaises(Exception):
                service.put(self.run, "VISUAL", "visual.test_stale", dict(technical=True))

    def test_competing_live_worker_cannot_complete_or_ack(self):
        with self.port.native(self.p, self.run, "read") as service:
            cfg = service.configuration(self.run, self.p.tenant)
            task = service.task_id(self.run, "VISUAL", 1)
            service.leases.acquire(task, cfg["fingerprint"], "other-live-worker", ttl_seconds=120)
        with self.assertRaises(Exception):
            self.step()
        with self.port.native(self.p, self.run, "read") as service:
            self.assertNotEqual(service.queue.get(task).state, "ACKED")

    def test_committed_tamper_prevents_recovery_ack(self):
        self.crash("after_VISUAL_terminal")
        self.tamper_stage("VISUAL")
        self.expire_test_lease()
        with self.assertRaises(Exception):
            self.port.recover(self.p, self.run)
        with self.port.native(self.p, self.run, "read") as service:
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 1)).state, "DELIVERED")

    def test_sync_catalog_tamper_blocks_restart(self):
        self.assertTrue(self.step()["slice_complete"])
        _, receipt = self.visual()
        with self.port.native(self.p, self.run, "read") as service:
            with closing(sqlite3.connect(service.root / "director-catalog.sqlite3")) as db:
                with db:
                    db.execute("UPDATE artifact_records SET record_json='{}' WHERE artifact_id=?",
                               (receipt["sync_ref"]["artifact_id"],))
        with self.assertRaises(Exception):
            self.port.status(self.p, self.run)

    def test_completed_recovery_replays_identity_without_new_attempt(self):
        expected = self.step()
        identity = self.visual()
        self.assertEqual(self.port.recover(self.p, self.run), expected)
        self.assertEqual(self.visual(), identity)
        with self.port.native(self.p, self.run, "read") as service:
            self.assertEqual(len(service.persistence.load_run_state(self.run)["stages"]["VISUAL"]["attempts"]), 1)

    def test_visual_worker_capability_does_not_unlock_historical_worker(self):
        from bie.productization.director_slice import DirectorProducerService
        old = DirectorProducerService.capability
        with self.port.native(self.p, self.run, "read") as service:
            self.assertIsNone(service.queue.poll("wrong-profile-worker", capability_tags=[old]))
            self.assertEqual(service.queue.get(service.task_id(self.run, "VISUAL", 1)).state, "READY")


if __name__ == "__main__":
    unittest.main()
