from __future__ import annotations
from .provenance_adapter import all_refs
import json
from .contracts import *
from .security import validate_generated_source
_GLYPH={'object':'●','vector':'→','graph':'∿','map':'⌖','timeline':'—●—','equation':'∑','label':'◆','model':'⬡','particle':'•','field':'◎','bio_structure':'◉','flow':'⇢'}

def compile_react_runtime(ctx:CompilerContext):
    ctx.validate();levels=[];profile=ctx.experience_profile;locale='en';direction='ltr';messages={'ui.ready':'Ready','ui.audio_play':'Play narration','ui.attribution':'Attribution'};attributions=[]
    if profile is not None:
        cat=profile.catalog();locale=cat.locale;direction=cat.direction;messages.update(cat.messages)
        required={'ui.ready','ui.audio_play','ui.attribution'}
        if not required.issubset(messages):raise GameCompilerError('GAME_COMP_LOCALIZATION_MESSAGES_MISSING')
        attributions=[{'asset_ref':r.asset_ref,'license_id':r.license_id,'attribution':r.attribution,'source_ref':r.source_ref,'rights_ref':r.rights_ref} for r in profile.rights]
        sync=profile.audio_sync_map()
    for exp in ctx.document.experiences:
      for level in exp.levels:
        title=messages.get('level:'+level.level_id+':title',level.title);purpose=messages.get('level:'+level.level_id+':purpose',level.purpose)
        levels.append({'game_id':exp.game_id,'level_id':level.level_id,'title':title,'purpose':purpose,
          'visual_entities':[{'id':v.entity_id,'kind':v.kind.value,'semantic_role':v.semantic_role,'state_bindings':list(v.state_bindings),'accessible_label':messages.get('entity:'+v.entity_id+':label',v.accessible_description),'glyph':_GLYPH[v.kind.value]} for v in level.visual.entities],
          'motion':[{'id':m.cue_id,'target':m.entity_id,'kind':m.kind.value,'start_ms':m.start_ms,'duration_ms':m.duration_ms,'purpose':m.pedagogical_purpose} for m in level.visual.motion],
          'camera':[{'id':c.cue_id,'kind':c.kind.value,'start_ms':c.start_ms,'duration_ms':c.duration_ms,'purpose':c.pedagogical_purpose,'target':c.target_entity_id} for c in level.visual.camera],
          'audio':[{'cue_id':a.cue_id,'kind':a.kind.value,'trigger_event':a.trigger_event,'asset_ref':a.asset_ref,'text_ref':a.text_ref,'duck_narration':a.duck_narration,'caption':ctx.text_catalog.get(a.text_ref,'') if a.text_ref else '', 'start_ms':(sync[a.cue_id].start_ms if profile is not None and a.cue_id in sync else 0),'end_ms':(sync[a.cue_id].end_ms if profile is not None and a.cue_id in sync else 0)} for a in level.audio.cues]})
    payload=json.dumps(levels,sort_keys=True,separators=(',',':'));config=json.dumps({'locale':locale,'direction':direction,'messages':messages,'attributions':attributions,'audio_max_sync_drift_ms':(profile.audio.max_sync_drift_ms if profile is not None else 120)},sort_keys=True,separators=(',',':'))
    ts=r'''export type StudioLevel = {game_id:string;level_id:string;title:string;purpose:string;visual_entities:readonly any[];motion:readonly any[];camera:readonly any[];audio:readonly any[]};
export const studioLevels:readonly StudioLevel[]=__PAYLOAD__ as const;
export const runtimeExperience=__CONFIG__ as const;
export function renderGameRuntime(React:{createElement:(...args:any[])=>any},activeLevelId:string):any{
 const level=studioLevels.find((x)=>x.level_id===activeLevelId);if(!level)throw new Error("GAME_LEVEL_NOT_FOUND");
 const nodes=level.visual_entities.map((e:any)=>{const tag=e.state_bindings.length?"button":"figure";const props:any={key:e.id,"data-entity-id":e.id,"data-entity-kind":e.kind,"data-semantic-role":e.semantic_role,"data-state-bindings":e.state_bindings.join(","),"aria-label":e.accessible_label};if(tag==="button")props.type="button";return React.createElement(tag,props,React.createElement("span",{"aria-hidden":"true"},e.glyph+" "),React.createElement("span",{"data-entity-label":"true"},e.accessible_label));});
 const audioButton=level.audio.length?React.createElement("button",{type:"button","data-audio-control":"play","aria-label":runtimeExperience.messages["ui.audio_play"]},runtimeExperience.messages["ui.audio_play"]):null;
 const rights=runtimeExperience.attributions.length?React.createElement("footer",{"data-rights-attribution":"true","aria-label":runtimeExperience.messages["ui.attribution"]},...runtimeExperience.attributions.map((r:any)=>React.createElement("p",{"data-rights-ref":r.rights_ref},r.attribution+" — "+r.license_id))):React.createElement("footer",{"data-rights-attribution":"true","aria-label":runtimeExperience.messages["ui.attribution"]},runtimeExperience.messages["ui.attribution"]);
 return React.createElement("main",{role:"application",lang:runtimeExperience.locale,dir:runtimeExperience.direction,"aria-label":level.title,"data-level-id":level.level_id,"data-studio-grade":"true","data-slide-deck":"false"},React.createElement("header",{},React.createElement("h2",{},level.title),React.createElement("p",{},level.purpose)),React.createElement("section",{"aria-label":"Interactive semantic scene","data-scene":"semantic"},...nodes),audioButton,React.createElement("output",{id:"bie-game-feedback","aria-live":"polite","aria-atomic":"true"},runtimeExperience.messages["ui.ready"]),React.createElement("div",{id:"bie-game-captions","aria-live":"polite","data-caption-region":"true"},""),rights);
}
export function hydrateSemanticPrimitives(activeLevelId:string):void{
 const level=studioLevels.find((x)=>x.level_id===activeLevelId);if(!level)throw new Error("GAME_LEVEL_NOT_FOUND");const NS="http:"+"//www.w3.org/2000/svg";
 for(const e of level.visual_entities as any[]){if(e.kind==="label")continue;const host=document.querySelector(`[data-entity-id="${e.id}"]`) as HTMLElement|null;if(!host)continue;if(host.querySelector('[data-semantic-svg]'))continue;const svg=document.createElementNS(NS,"svg");svg.setAttribute("data-semantic-svg","true");svg.setAttribute("viewBox","0 0 180 96");svg.setAttribute("width","180");svg.setAttribute("height","96");svg.setAttribute("role","img");svg.setAttribute("aria-label",e.accessible_label);
 const line=(x1:number,y1:number,x2:number,y2:number)=>{const n=document.createElementNS(NS,"line");n.setAttribute("x1",String(x1));n.setAttribute("y1",String(y1));n.setAttribute("x2",String(x2));n.setAttribute("y2",String(y2));n.setAttribute("stroke","currentColor");n.setAttribute("stroke-width","3");svg.appendChild(n);};
 const circle=(cx:number,cy:number,r:number)=>{const n=document.createElementNS(NS,"circle");n.setAttribute("cx",String(cx));n.setAttribute("cy",String(cy));n.setAttribute("r",String(r));n.setAttribute("fill","none");n.setAttribute("stroke","currentColor");n.setAttribute("stroke-width","3");svg.appendChild(n);};
 if(e.kind==="vector"){line(18,48,150,48);const p=document.createElementNS(NS,"polygon");p.setAttribute("points","150,38 170,48 150,58");p.setAttribute("fill","currentColor");svg.appendChild(p);} else if(e.kind==="graph"){line(24,78,24,18);line(24,78,162,78);const poly=document.createElementNS(NS,"polyline");poly.setAttribute("points","28,70 60,58 92,62 126,32 158,24");poly.setAttribute("fill","none");poly.setAttribute("stroke","currentColor");poly.setAttribute("stroke-width","3");svg.appendChild(poly);} else if(e.kind==="map"){const r=document.createElementNS(NS,"rect");r.setAttribute("x","20");r.setAttribute("y","16");r.setAttribute("width","140");r.setAttribute("height","64");r.setAttribute("fill","none");r.setAttribute("stroke","currentColor");svg.appendChild(r);circle(60,46,6);circle(126,58,6);line(66,48,120,56);} else if(e.kind==="timeline"){line(18,48,162,48);circle(48,48,6);circle(90,48,6);circle(136,48,6);} else if(e.kind==="equation"){const t=document.createElementNS(NS,"text");t.setAttribute("x","24");t.setAttribute("y","56");t.setAttribute("font-size","24");t.textContent="x = f(state)";svg.appendChild(t);} else if(e.kind==="particle"){circle(90,48,20);} else if(e.kind==="field"){circle(90,48,18);circle(90,48,34);circle(90,48,46);} else if(e.kind==="flow"){circle(36,48,10);circle(90,48,10);circle(144,48,10);line(46,48,80,48);line(100,48,134,48);} else if(e.kind==="bio_structure"){circle(90,48,34);circle(78,44,8);circle(108,54,6);} else {const r=document.createElementNS(NS,"rect");r.setAttribute("x","34");r.setAttribute("y","20");r.setAttribute("width","112");r.setAttribute("height","56");r.setAttribute("rx","12");r.setAttribute("fill","none");r.setAttribute("stroke","currentColor");r.setAttribute("stroke-width","3");svg.appendChild(r);} host.appendChild(svg);}
}
export function applySemanticState(state:Record<string,unknown>,activeLevelId:string):void{
 const level=studioLevels.find((x)=>x.level_id===activeLevelId);if(!level)throw new Error("GAME_LEVEL_NOT_FOUND");const reduced=globalThis.matchMedia?.("(prefers-reduced-motion: reduce)").matches===true;
 for(const e of level.visual_entities as any[]){const node=document.querySelector(`[data-entity-id="${e.id}"]`) as HTMLElement|null;if(!node)continue;const values=e.state_bindings.map((k:string)=>[k,state[k]]);node.dataset.stateValue=JSON.stringify(values);const cue=(level.motion as any[]).find((m:any)=>m.target===e.id);if(cue){node.dataset.motionKind=cue.kind;if(!reduced&&typeof node.animate==="function"){const numeric=values.find((x:any)=>typeof x[1]==="number");const distance=numeric?Math.max(-120,Math.min(120,Number(numeric[1])*16)):24;node.animate([{transform:"translateX(0px)",opacity:.8},{transform:`translateX(${distance}px)`,opacity:1}],{duration:Math.max(120,cue.duration_ms),fill:"forwards",easing:"ease"});}}}
 const cam=(level.camera as any[])[0];const root=document.querySelector('main[role="application"]') as HTMLElement|null;if(root&&cam){root.dataset.cameraKind=cam.kind;if(cam.target)root.dataset.cameraTarget=cam.target;const target=cam.target?document.querySelector(`[data-entity-id="${cam.target}"]`) as HTMLElement|null:null;if(target&&!reduced&&typeof target.animate==="function")target.animate([{transform:"scale(1)"},{transform:"scale(1.04)"}],{duration:Math.max(120,cam.duration_ms),direction:"alternate",iterations:2,easing:"ease-in-out"});}}
export function renderedGeometry(activeLevelId:string):readonly {id:string;width:number;height:number;text:string}[]{const level=studioLevels.find((x)=>x.level_id===activeLevelId);if(!level)throw new Error("GAME_LEVEL_NOT_FOUND");return level.visual_entities.map((e:any)=>{const n=document.querySelector(`[data-entity-id="${e.id}"]`) as HTMLElement|null;const r=n?.getBoundingClientRect();return{id:e.id,width:r?.width||0,height:r?.height||0,text:(n?.textContent||"").trim()};});}
'''.replace('__PAYLOAD__',payload).replace('__CONFIG__',config)
    validate_generated_source(ts);return artifact(ArtifactKind.REACT_RUNTIME,'runtime/react-runtime.ts','text/typescript',ts,all_refs(ctx.document.provenance))
