import os,json,sys
from pathlib import Path
MODEL=os.getenv("BIE_MODEL","gpt-5.6-luna")
SCHEMA={"type": "object", "additionalProperties": false, "required": ["unit_id", "title", "source_refs", "claims", "question_matrix", "definitions", "processes", "causes", "time_place", "people_entities", "applications", "derivations", "higher_knowledge_candidates", "dependencies", "uncertainties", "confidence", "review_required"], "properties": {"unit_id": {"type": "string"}, "title": {"type": "string"}, "source_refs": {"type": "array", "items": {"type": "string"}}, "claims": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["claim_id", "text", "evidence_refs", "status"], "properties": {"claim_id": {"type": "string"}, "text": {"type": "string"}, "evidence_refs": {"type": "array", "items": {"type": "string"}}, "status": {"type": "string", "enum": ["GROUNDED", "UNCERTAIN", "UNSUPPORTED"]}}}}, "question_matrix": {"type": "object", "additionalProperties": false, "properties": {"what": {"type": "array", "items": {"type": "string"}}, "why": {"type": "array", "items": {"type": "string"}}, "how": {"type": "array", "items": {"type": "string"}}, "when": {"type": "array", "items": {"type": "string"}}, "where": {"type": "array", "items": {"type": "string"}}, "who": {"type": "array", "items": {"type": "string"}}, "derivation": {"type": "array", "items": {"type": "string"}}, "application": {"type": "array", "items": {"type": "string"}}}}, "definitions": {"type": "array", "items": {"type": "string"}}, "processes": {"type": "array", "items": {"type": "string"}}, "causes": {"type": "array", "items": {"type": "string"}}, "time_place": {"type": "array", "items": {"type": "string"}}, "people_entities": {"type": "array", "items": {"type": "string"}}, "applications": {"type": "array", "items": {"type": "string"}}, "derivations": {"type": "array", "items": {"type": "string"}}, "higher_knowledge_candidates": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["claim", "status"], "properties": {"claim": {"type": "string"}, "status": {"type": "string", "enum": ["CANDIDATE", "EXTERNAL_RESEARCH"]}}}}, "dependencies": {"type": "array", "items": {"type": "object", "additionalProperties": false, "required": ["target_unit", "relation", "confidence"], "properties": {"target_unit": {"type": "string"}, "relation": {"type": "string"}, "confidence": {"type": "number", "minimum": 0, "maximum": 1}}}}, "uncertainties": {"type": "array", "items": {"type": "string"}}, "confidence": {"type": "number", "minimum": 0, "maximum": 1}, "review_required": {"type": "boolean"}}}
SYSTEM="""You are the BIE source-grounded book understanding engine. Extract only what the supplied excerpts support. Every source-derived claim needs evidence_refs. Never silently correct or reconcile the book. Mark ambiguity as uncertainty/review. Keep outside knowledge separate as higher_knowledge_candidates. Return only schema-valid JSON."""
def run(excerpts,out):
    key=os.getenv("OPENAI_API_KEY")
    if not key: raise RuntimeError("OPENAI_API_KEY is missing from the environment.")
    from openai import OpenAI
    client=OpenAI(api_key=key)
    r=client.responses.create(model=MODEL,input=[{"role":"system","content":SYSTEM},{"role":"user","content":json.dumps({"excerpts":excerpts})}],text={"format":{"type":"json_schema","name":"bie_book_unit","strict":True,"schema":SCHEMA}})
    Path(out).write_text(json.dumps(json.loads(r.output_text),indent=2,ensure_ascii=False))
if __name__=="__main__":
    run(json.loads(Path(sys.argv[1]).read_text()),sys.argv[2])
