QUESTION_TYPES = [
    "WHAT", "WHY", "HOW", "WHEN", "WHERE", "WHO", "WHICH", "HOW_MUCH", "HOW_MANY",
    "WHAT_IF", "WHAT_CAUSES", "WHAT_RESULT", "HOW_DERIVED", "UNDER_WHAT_ASSUMPTION",
    "HOW_DO_WE_KNOW", "WHAT_EVIDENCE", "WHERE_APPLIED", "WHY_APPLIED", "COMPARISON",
    "LIMITATION", "EXCEPTION", "WHAT_DEPENDS_ON_IT", "WHAT_DOES_IT_ENABLE", "WHAT_COMES_NEXT"
]
